services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=product
      - DATABASE_URL=postgresql://celine:password@db:5432/todo
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_SECRET=your-secret-key-here
      - AUTH_GOOGLE_ID=dummy-google-id
      - AUTH_GOOGLE_SECRET=dummy-google-secret
    depends_on:
      - db
    networks:
      - app-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=celine
      - POSTGRES_PASSWORD=celine45
      - POSTGRES_DB=todo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
