version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app
    ports:
      - "3000:3000"
    env_file:
      - .env # Load DATABASE_URL=postgresql://celine:celine45@localhost:5433/todo
    network_mode: host # Use host network to access VM's PostgreSQL at localhost:5433