version: '3.8'
services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app
    ports:
      - "3000:3000"
    env_file:
      - .env  # Load environment variables from .env file
    # depends_on:
    #   - db
    networks:
      - app-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    env_file:
      - .env  # Load database credentials from .env
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge