version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app
    ports:
      - "3000:3000"
    env_file:
      - .env # Load environment variables, including DATABASE_URL
    networks:
      - app-network
    # Use host network to allow container to reach VM's PostgreSQL
    network_mode: host

networks:
  app-network:
    driver: bridge